# Generated by Django 5.2.5 on 2026-03-26 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0003_remove_assignment_student_assignmentsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='assignmentsubmission',
            name='grade',
        ),
    ]
