# Generated by Django 5.2.5 on 2026-03-26 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0004_remove_assignmentsubmission_feedback_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
