# Generated by Django 5.2.5 on 2026-03-26 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0006_projectsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='student',
        ),
    ]
