# Generated by Django 5.2.5 on 2026-03-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0007_remove_project_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsubmission',
            name='file',
            field=models.FileField(upload_to='assignment_submissions/'),
        ),
    ]
