# Generated by Django 5.2.5 on 2026-03-26 21:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0008_alter_assignmentsubmission_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizattempt',
            name='completed',
        ),
        migrations.AddField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(),
        ),
    ]
